name: tools
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  path: ^1.8.3
  args: any
  flutter:
   sdk: flutter
  analyzer: ^6.2.0
  phosphor_flutter: ^2.0.0

dev_dependencies:
  grinder: ^0.9.4
  lints: ^2.1.1
